### ISSUE TITLE
Duplicate classes when using the Android Studio gradle build

### ISSUE THREAD

**Issue by svetlin** [CUTR-at-USF/SiriRestClient#9]
This issue is not about Siri, but about the modified Jackson xml libs in general.
I'd post on StackOverflow, but I don't have a reputation of 10 there yet:
http://stackoverflow.com/questions/5461127/using-jaxb-with-google-android
And I don't see a more relevant project of CUTR-at-USF to file the issue with, so here it goes (sorry).

I'm using the AS build.gradle snippet from the SO article without actually referring to it in my code, just building, and I'm getting this error:
`Error:duplicate files during packaging of APK /home/some_user/git/some_project/app/build/outputs/apk/app-external-debug-unaligned.apk
    Path in archive: META-INF/services/com.fasterxml.jackson.core.ObjectCodec
    Origin 1: /home/some_user/.gradle/caches/modules-2/files-2.1/edu.usf.cutr.android.xml/jackson-dataformat-xml-android/2.1.2/68f331ff4682ab057877b2b5705694ef600ce67e/jackson-dataformat-xml-android-2.1.2.jar
    Origin 2: /home/some_user/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.1.2/e9c672d2d60c966772c6271d5a61614a4259274a/jackson-databind-2.1.2.jar
You can ignore those files in your build.gradle:
    android {
      packagingOptions {
        exclude 'META-INF/services/com.fasterxml.jackson.core.ObjectCodec'
      }`

Once I indeed ignore this file, I get a similar error to ignore another file from the manifest. I wonder how safe is that even if possible.

**Comment by barbeau** [comment]
@svetlin I've gotten reports from others that there are some issues with the JSR173 provider being registered with the more recent Android Studio / Android Gradle Plugin.  I'm not actively using XML parsing (we use JSON), so I haven't seen it myself.

Take a look at these two issues, which has some discussion of the issue you reference above:
- http://stackoverflow.com/questions/31360025/using-jackson-dataformat-xml-on-android
- http://stackoverflow.com/questions/30968735/using-com-bea-xml-stream-package-on-android

I believe there are a few bugs (referenced in the comments on the above SO posts) in Android Studio / Android gradle plugin that are affecting this.

**Comment by tigabGhub** [comment]
~~~
Duplicate class org.kxml2.io.KXmlParser found in modules ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar (ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar) and kxml2-2.3.0.jar (net.sf.kxml:kxml2:2.3.0)
Duplicate class org.kxml2.io.KXmlSerializer found in modules ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar (ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar) and kxml2-2.3.0.jar (net.sf.kxml:kxml2:2.3.0)
Duplicate class org.kxml2.kdom.Document found in modules ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar (ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar) and kxml2-2.3.0.jar (net.sf.kxml:kxml2:2.3.0)
Duplicate class org.kxml2.kdom.Element found in modules ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar (ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar) and kxml2-2.3.0.jar (net.sf.kxml:kxml2:2.3.0)
Duplicate class org.kxml2.kdom.Node found in modules ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar (ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar) and kxml2-2.3.0.jar (net.sf.kxml:kxml2:2.3.0)
Duplicate class org.kxml2.wap.Wbxml found in modules ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar (ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar) and kxml2-2.3.0.jar (net.sf.kxml:kxml2:2.3.0)
Duplicate class org.kxml2.wap.WbxmlParser found in modules ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar (ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar) and kxml2-2.3.0.jar (net.sf.kxml:kxml2:2.3.0)
Duplicate class org.kxml2.wap.WbxmlSerializer found in modules ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar (ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar) and kxml2-2.3.0.jar (net.sf.kxml:kxml2:2.3.0)
Duplicate class org.kxml2.wap.syncml.SyncML found in modules ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar (ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar) and kxml2-2.3.0.jar (net.sf.kxml:kxml2:2.3.0)
Duplicate class org.kxml2.wap.wml.Wml found in modules ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar (ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar) and kxml2-2.3.0.jar (net.sf.kxml:kxml2:2.3.0)
Duplicate class org.kxml2.wap.wv.WV found in modules ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar (ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar) and kxml2-2.3.0.jar (net.sf.kxml:kxml2:2.3.0)
Duplicate class org.xmlpull.v1.XmlPullParser found in modules ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar (ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar) and kxml2-2.3.0.jar (net.sf.kxml:kxml2:2.3.0)
Duplicate class org.xmlpull.v1.XmlPullParserException found in modules ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar (ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar) and kxml2-2.3.0.jar (net.sf.kxml:kxml2:2.3.0)
Duplicate class org.xmlpull.v1.XmlPullParserFactory found in modules ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar (ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar) and kxml2-2.3.0.jar (net.sf.kxml:kxml2:2.3.0)
Duplicate class org.xmlpull.v1.XmlSerializer found in modules ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar (ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar) and kxml2-2.3.0.jar (net.sf.kxml:kxml2:2.3.0)
~~~

Go to the documentation to learn how to Fix dependency resolution errors.
 i have the same problem

**Comment by tigabGhub** [comment]
my build.gradle  file is

~~~
apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.example.my_map"
        minSdkVersion 14
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    androidTestImplementation('com.android.support.test.espresso:espresso-core:3.0.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    implementation files('libs/gson-2.6.2.jar')
  //  implementation files('libs/ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar')
    //noinspection GradleCompatible
    implementation 'com.android.support:design:28.0.0'

    //noinspection UseOfBundledGooglePlayServices
    implementation 'com.google.android.gms:play-services:12.0.1'
    implementation 'com.android.support:support-v4:28.0.0'
    //noinspection GradleDynamicVersion
    implementation 'com.google.maps.android:android-maps-utils:0.5+'
    implementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    testImplementation 'junit:junit:4.12'
    implementation 'com.google.guava:guava:24.1-jre'
    implementation 'android.arch.navigation:navigation-fragment:1.0.0'
    implementation 'com.android.support:appcompat-v7:28.0.0'
   implementation 'android.arch.navigation:navigation-ui:1.0.0'
 implementation 'com.android.databinding:baseLibrary:3.4.1'

}
~~~
   if some one help me i have big respect

**Comment by 3boodev** [comment]
> 
> 
> my build.gradle file is
> 
> ```
> apply plugin: 'com.android.application'
> 
> android {
>     compileSdkVersion 28
>     defaultConfig {
>         applicationId "com.example.my_map"
>         minSdkVersion 14
>         targetSdkVersion 28
>         versionCode 1
>         versionName "1.0"
>         testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
>         multiDexEnabled true
>     }
>     buildTypes {
>         release {
>             minifyEnabled false
>             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
>         }
>     }
> }
> 
> dependencies {
>     implementation fileTree(include: ['*.jar'], dir: 'libs')
>     implementation 'com.android.support.constraint:constraint-layout:1.1.3'
>     androidTestImplementation('com.android.support.test.espresso:espresso-core:3.0.2', {
>         exclude group: 'com.android.support', module: 'support-annotations'
>     })
>     implementation files('libs/gson-2.6.2.jar')
>   //  implementation files('libs/ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar')
>     //noinspection GradleCompatible
>     implementation 'com.android.support:design:28.0.0'
> 
>     //noinspection UseOfBundledGooglePlayServices
>     implementation 'com.google.android.gms:play-services:12.0.1'
>     implementation 'com.android.support:support-v4:28.0.0'
>     //noinspection GradleDynamicVersion
>     implementation 'com.google.maps.android:android-maps-utils:0.5+'
>     implementation 'com.android.support.test.espresso:espresso-core:3.0.2'
>     testImplementation 'junit:junit:4.12'
>     implementation 'com.google.guava:guava:24.1-jre'
>     implementation 'android.arch.navigation:navigation-fragment:1.0.0'
>     implementation 'com.android.support:appcompat-v7:28.0.0'
>    implementation 'android.arch.navigation:navigation-ui:1.0.0'
>  implementation 'com.android.databinding:baseLibrary:3.4.1'
> 
> }
> ```
> 
> if some one help me i have big respect

Are you Find Solution , because I have the same Error.

**Comment by ghost** [comment]
Same error with Firebase library
